color0 #464651
color1 #ffb4ab
color2 #cacdff
color3 #c2c4e7
color4 #ffbcef
color5 #bdc2ff
color6 #c2c4e7
color7 #e4e1e8
color8 #908f9c
color9 #ffb4ab
color10 #cacdff
color11 #c2c4e7
color12 #ffbcef
color13 #bdc2ff
color14 #c2c4e7
color15 #e4e1e8

cursor                #e4e1e8
cursor_text_color     #131318
background            #131318
foreground            #e4e1e8
selection_foreground  #c7c5d2
selection_background  #464651
active_border_color   #cacdff
inactive_border_color #464651
url_color             #cacdff

active_tab_foreground   #212870
active_tab_background   #cacdff
inactive_tab_foreground #c7c5d2
inactive_tab_background #464651
cursor_trail_color      #c7c5d2
