name: build parchiso per release
on:
  release:
    types:
      - created
env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
  VARIANT: hyprland
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v7
      - name: Install Packages via Pacman
        run: pacman -Syu --noconfirm; pacman --noconfirm -S git archiso python python-pygithub github-cli reflector p7zip openssh sshpass rsync wget
      - name: Change mirrors
        run: reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
      - name: Build image
        run: mkarchiso -v iso/
      - name: remove last iso
        run: sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no parch@${{ secrets.SSH_HOST }} rm -rf /srv/http/${VARIANT}/
      - name: recreate iso dir
        run: sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no parch@${{ secrets.SSH_HOST }} mkdir /srv/http/${VARIANT}/
      - name: rename iso
        run: mv "$(ls out/*.iso)" out/Parchlinux-${VARIANT}-latest.iso
      - name: generate md5
        run: |
          ISO_FILE="out/Parchlinux-${VARIANT}-latest.iso"
          md5sum "$ISO_FILE" > out/md5sum.txt
      - name: upload iso to host
        run: sshpass -p "${{ secrets.SSH_PASS }}" rsync -r out/Parchlinux-${VARIANT}-latest.iso parch@${{ secrets.SSH_HOST }}:/srv/http/${VARIANT}/
      - name: upload md5 to host
        run: sshpass -p "${{ secrets.SSH_PASS }}" rsync -r out/md5sum.txt parch@${{ secrets.SSH_HOST }}:/srv/http/${VARIANT}/
